# Generated by Django 5.1.3 on 2024-11-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
