# Generated by Django 5.1.3 on 2024-11-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_tag_remove_blogpost_tag_blogpost_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
